# Generated by Django 5.1.6 on 2025-03-02 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_dataengagement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataEngagement',
        ),
    ]
