# Generated by Django 5.1.6 on 2025-03-02 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cameras', '0009_delete_dataengagement'),
        ('app_users', '0003_delete_dataengagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reasons_for_visit', models.JSONField(default=list)),
                ('travel_with', models.CharField(choices=[('alone', 'Alone'), ('family', 'With family'), ('friends', 'With friends'), ('tour_group', 'With a tour group')], max_length=20)),
                ('location_satisfaction', models.IntegerField(choices=[(1, '😡'), (2, '😞'), (3, '😑'), (4, '🙂'), (5, '😍')])),
                ('location_comment', models.TextField(blank=True, null=True)),
                ('elevview_satisfaction', models.IntegerField(choices=[(1, '😡'), (2, '😞'), (3, '😑'), (4, '🙂'), (5, '😍')])),
                ('elevview_comment', models.TextField(blank=True, null=True)),
                ('planning_ahead', models.CharField(choices=[('last_minute', 'No prior planning (last-minute decision)'), ('1_3_days', '1-3 days in advance'), ('1_4_weeks', '1-4 weeks in advance'), ('more_than_1_month', 'More than 1 month in advance')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='app_cameras.photo')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='app_users.profile')),
            ],
        ),
    ]
