# Generated by Django 5.1.6 on 2025-03-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0005_remove_profile_address_remove_profile_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ages',
            field=models.CharField(default='', max_length=3),
        ),
    ]
