# Generated by Django 5.1.4 on 2025-01-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cameras', '0002_alter_camera_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='ชื่อ',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
