# Generated by Django 5.1.4 on 2025-01-13 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cameras', '0003_camera_ช_อ'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='ชื่อ',
            new_name='name_thai',
        ),
    ]
