# Generated by Django 5.1.4 on 2025-01-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cameras', '0004_rename_ช_อ_camera_name_thai'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='qr_code',
            field=models.CharField(default='XXX', max_length=255),
        ),
    ]
