# Generated by Django 5.1.4 on 2025-01-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cameras', '0005_camera_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='qr_code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
