# Generated by Django 5.1.6 on 2025-03-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cameras', '0006_alter_camera_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.URLField(),
        ),
    ]
