# Generated by Django 5.1.6 on 2025-03-02 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cameras', '0008_dataengagement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataEngagement',
        ),
    ]
