# Generated by Django 5.1.6 on 2025-03-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cameras', '0009_delete_dataengagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='preview_image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
