# Generated by Django 5.1.6 on 2025-03-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cameras', '0010_camera_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='preview_image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
